### ISSUE TITLE
caffe doesn't compile

### ISSUE THREAD

**Issue by cyrenaique** [willyd/caffe-builder#1]
build\caffe-prefix\src\caffe-build\include\caffe\proto\caffe.pb.h(17): fatal error C1189: #error :  This file was generated by an older version of protoc which is...

No ideas! :-), this file is auto generated at the build if understood well...

**Comment by willyd** [comment]
Weird, never got that one. Do you have a conflict between a previously installed protobuf library? What path is the CMake variable PROTOBUF_PROTOC_EXECUTABLE pointing to?

**Comment by cyrenaique** [comment]
Well, it's actually the case, I had an old protoc in my path, and totally forgot about that one. Trying to fix that I messed up everything (just realized that), so I will restart from scratch and let you know. Does it compile with OPENCV3.0 or I should stick on OPENCV 2? Anyway thanks for feedback and good guess!

**Comment by willyd** [comment]
Good that you solved your problem. 

Yes it can compile with OpenCV 3. I just pushed a new branch [opencv3-support](https://github.com/willyd/caffe-builder/tree/opencv3-support) with (experimental) support for OpenCV 3.x. You can try it if you like.

**Comment by cyrenaique** [comment]
Cool! big thanks for your awesome job! Still not finished to compile but seems much better :-)...I will try with OPENCV3 and let you know.

**Comment by cyrenaique** [comment]
With Cmake-Gui and a just naive configure pushed, it's still downloading OPENCV2.4, I checked the cmake file OPENCV-download and I guess the condition isn't satisfied with just configure...

**Comment by willyd** [comment]
Can't you check the option in the CMake-GUI? You can also try to delete the cache and reconfigure. It should not redownload everything but the builds my be considered outdated.

**Comment by cyrenaique** [comment]
I was talking about OpenCV.cmake in packages, I didn't have any option in the gui...The weird stuff that the download link of github of this branch is also the same name like caffe-builder-master.zip and now when I download I got the bad zip file (2.4 I mean, not so bad :-)).

**Comment by cyrenaique** [comment]
I added an entry in the cmakegui BUILD_OPENCV3(bool=true) and now it works...

**Comment by cyrenaique** [comment]
Ok, now I have the option, I think I am just tired...sorry for that
